#karacsonyfa
print("        ☆")
print("       ####  ")
print("      ######  ")
print("     ########  ")
print("    ##########  ")
print("   ############  ")
print("        ||  ")
print("        ||  ")
print("     ########  ")
print("    ##########  ")
print("   ############  ")
print("        ||  ")
print("        ||  ")
print("        ||  ")
print("        ||  ")
print("        ||  ")
print("        ||  ")
